definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: app
        MYSQL_USER: user
        MYSQL_PASSWORD: password

pipelines:
  branches:
    "devops":
      - step:
          name: Run Tests - PHP 8.4, Laravel 11
          image: php:8.4
          services:
            - mysql
          caches:
            - composer
          script:
            - export LARAVEL_VERSION=11
              apt-get update && apt-get install -y \
              git \
              unzip \
              zip \
              curl \
              ca-certificates \
              lsb-release \
              apt-transport-https \
              gnupg \
              software-properties-common
            - apt-get update && apt-get install -y libxml2-dev libcurl4-openssl-dev libpng-dev libjpeg-dev libfreetype6-dev
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer update --prefer-dist --no-interaction --no-progress --with="illuminate/contracts=^11"
            - vendor/bin/phpunit --display-deprecations --fail-on-deprecation 
