clone:
  depth: full

options:
  docker: true

image: threadable/linuxnginxphp_ci_20.04:2025.01.01

pipelines:
  branches:
    "{feature/*,bugfix/*}":

      - step:
          name: Check CI Build
          script:
            - COMMIT_MSG="$(git log -1 --pretty=format:%s)"
            - if [[ $COMMIT_MSG != "[CI]"* ]]; then exit 1; fi

      - step:
          name: Submit to CI/CD
          script:
            - set +e
            - if [[ $BITBUCKET_BRANCH =~ ([A-Za-z0-9]+-[0-9]+) ]]; then export JIRA_ISSUE=${BASH_REMATCH[1]}; else exit 0; fi
            - pipe: atlassian/jira-transition:0.5.1

              variables:
                JIRA_BASE_URL: $JIRA_BASE_URL
                JIRA_USER_EMAIL: $JIRA_USER_EMAIL
                JIRA_API_TOKEN: $JIRA_API_TOKEN
                ISSUE: $JIRA_ISSUE
                TRANSITION: 'Submit to CI/CD'
            - set -e

      - step: 
          name: Static Analysis
          size: 2x
          image: threadable/php84-laravel
          caches:
            - docker
            - composer
          script:
            - composer update --prefer-dist --no-interaction --no-progress --with="illuminate/contracts=^11"
            - vendor/bin/phpstan
          after-script:
            - if [[ BITBUCKET_EXIT_CODE -eq 0 ]]; then exit 0; fi
            - set +e
            - if [[ $BITBUCKET_BRANCH =~ ([A-Za-z0-9]+-[0-9]+) ]]; then export JIRA_ISSUE=${BASH_REMATCH[1]}; else exit 0; fi
            - pipe: atlassian/jira-transition:0.5.1
              variables:
                JIRA_BASE_URL: $JIRA_BASE_URL
                JIRA_USER_EMAIL: $JIRA_USER_EMAIL
                JIRA_API_TOKEN: $JIRA_API_TOKEN
                ISSUE: $JIRA_ISSUE
                TRANSITION: 'Failed CI'
            - set -e
      
      - step:
          name: Run Tests - PHP 8.1, Laravel 10
          size: 2x
          image: threadable/php81-laravel
          caches:
            - docker
            - composer
          script:
            - composer update --prefer-dist --no-interaction --no-progress --with="illuminate/contracts=^10"
            - vendor/bin/phpunit --display-deprecations --fail-on-deprecation
          after-script:
            - if [[ BITBUCKET_EXIT_CODE -eq 0 ]]; then exit 0; fi
            - set +e
            - if [[ $BITBUCKET_BRANCH =~ ([A-Za-z0-9]+-[0-9]+) ]]; then export JIRA_ISSUE=${BASH_REMATCH[1]}; else exit 0; fi
            - pipe: atlassian/jira-transition:0.5.1
              variables:
                JIRA_BASE_URL: $JIRA_BASE_URL
                JIRA_USER_EMAIL: $JIRA_USER_EMAIL
                JIRA_API_TOKEN: $JIRA_API_TOKEN
                ISSUE: $JIRA_ISSUE
                TRANSITION: 'Failed CI'
            - set -e

      - step:
          name: Run Tests - PHP 8.2, Laravel 10
          size: 2x
          image: threadable/php82-laravel
          caches:
            - docker
            - composer
          script:
            - composer update --prefer-dist --no-interaction --no-progress --with="illuminate/contracts=^10"
            - vendor/bin/phpunit --display-deprecations --fail-on-deprecation
          after-script:
            - if [[ BITBUCKET_EXIT_CODE -eq 0 ]]; then exit 0; fi
            - set +e
            - if [[ $BITBUCKET_BRANCH =~ ([A-Za-z0-9]+-[0-9]+) ]]; then export JIRA_ISSUE=${BASH_REMATCH[1]}; else exit 0; fi
            - pipe: atlassian/jira-transition:0.5.1
              variables:
                JIRA_BASE_URL: $JIRA_BASE_URL
                JIRA_USER_EMAIL: $JIRA_USER_EMAIL
                JIRA_API_TOKEN: $JIRA_API_TOKEN
                ISSUE: $JIRA_ISSUE
                TRANSITION: 'Failed CI'
            - set -e

      - step:
          name: Run Tests - PHP 8.3, Laravel 10
          size: 2x
          image: threadable/php83-laravel
          caches:
            - docker
            - composer
          script:
            - composer update --prefer-dist --no-interaction --no-progress --with="illuminate/contracts=^10"
            - vendor/bin/phpunit --display-deprecations --fail-on-deprecation
          after-script:
            - if [[ BITBUCKET_EXIT_CODE -eq 0 ]]; then exit 0; fi
            - set +e
            - if [[ $BITBUCKET_BRANCH =~ ([A-Za-z0-9]+-[0-9]+) ]]; then export JIRA_ISSUE=${BASH_REMATCH[1]}; else exit 0; fi
            - pipe: atlassian/jira-transition:0.5.1
              variables:
                JIRA_BASE_URL: $JIRA_BASE_URL
                JIRA_USER_EMAIL: $JIRA_USER_EMAIL
                JIRA_API_TOKEN: $JIRA_API_TOKEN
                ISSUE: $JIRA_ISSUE
                TRANSITION: 'Failed CI'
            - set -e

      - step:
          name: Run Tests - PHP 8.2, Laravel 11
          size: 2x
          image: threadable/php82-laravel
          caches:
            - docker
            - composer
          script:
            - composer update --prefer-dist --no-interaction --no-progress --with="illuminate/contracts=^11"
            - vendor/bin/phpunit --display-deprecations --fail-on-deprecation
          after-script:
            - if [[ BITBUCKET_EXIT_CODE -eq 0 ]]; then exit 0; fi
            - set +e
            - if [[ $BITBUCKET_BRANCH =~ ([A-Za-z0-9]+-[0-9]+) ]]; then export JIRA_ISSUE=${BASH_REMATCH[1]}; else exit 0; fi
            - pipe: atlassian/jira-transition:0.5.1
              variables:
                JIRA_BASE_URL: $JIRA_BASE_URL
                JIRA_USER_EMAIL: $JIRA_USER_EMAIL
                JIRA_API_TOKEN: $JIRA_API_TOKEN
                ISSUE: $JIRA_ISSUE
                TRANSITION: 'Failed CI'
            - set -e

      - step:
          name: Run Tests - PHP 8.3, Laravel 11
          size: 2x
          image: threadable/php83-laravel
          caches:
            - docker
            - composer
          script:
            - composer update --prefer-dist --no-interaction --no-progress --with="illuminate/contracts=^11"
            - vendor/bin/phpunit --display-deprecations --fail-on-deprecation
          after-script:
            - if [[ BITBUCKET_EXIT_CODE -eq 0 ]]; then exit 0; fi
            - set +e
            - if [[ $BITBUCKET_BRANCH =~ ([A-Za-z0-9]+-[0-9]+) ]]; then export JIRA_ISSUE=${BASH_REMATCH[1]}; else exit 0; fi
            - pipe: atlassian/jira-transition:0.5.1
              variables:
                JIRA_BASE_URL: $JIRA_BASE_URL
                JIRA_USER_EMAIL: $JIRA_USER_EMAIL
                JIRA_API_TOKEN: $JIRA_API_TOKEN
                ISSUE: $JIRA_ISSUE
                TRANSITION: 'Failed CI'
            - set -e

      - step:
          name: Run Tests - PHP 8.4, Laravel 11 & Code Coverage
          size: 2x
          image: threadable/php84-laravel
          caches:
            - docker
            - composer
          script:
            - composer update --prefer-dist --no-interaction --no-progress --with="illuminate/contracts=^11"
            - vendor/bin/phpunit --display-deprecations --fail-on-deprecation
            - pipe: sonarsource/sonarcloud-scan:2.0.0
              variables:
                DEBUG: "true"
                SONAR_SCANNER_OPTS: -Xmx2048m
            - pipe: sonarsource/sonarcloud-quality-gate:0.1.6
          after-script:
            - if [[ BITBUCKET_EXIT_CODE -eq 0 ]]; then exit 0; fi
            - set +e
            - if [[ $BITBUCKET_BRANCH =~ ([A-Za-z0-9]+-[0-9]+) ]]; then export JIRA_ISSUE=${BASH_REMATCH[1]}; else exit 0; fi
            - pipe: atlassian/jira-transition:0.5.1
              variables:
                JIRA_BASE_URL: $JIRA_BASE_URL
                JIRA_USER_EMAIL: $JIRA_USER_EMAIL
                JIRA_API_TOKEN: $JIRA_API_TOKEN
                ISSUE: $JIRA_ISSUE
                TRANSITION: 'Failed CI'
            - set -e

      - step:
          name: Ready for QA
          script:
            - set +e
            - if [[ $BITBUCKET_BRANCH =~ ([A-Za-z0-9]+-[0-9]+) ]]; then export JIRA_ISSUE=${BASH_REMATCH[1]}; else exit 1; fi
            - pipe: atlassian/jira-transition:0.5.1
              variables:
                JIRA_BASE_URL: $JIRA_BASE_URL
                JIRA_USER_EMAIL: $JIRA_USER_EMAIL
                JIRA_API_TOKEN: $JIRA_API_TOKEN
                ISSUE: $JIRA_ISSUE
                TRANSITION: 'Passed CI'
            - set -e

      - step:
          name: PR to QA
          script:
            - echo $BITBUCKET_REPO_FULL_NAME
            - echo "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_FULL_NAME}/pullrequests"
            - apt-get update && apt-get install -y jq
            - export PR_TITLE=$BITBUCKET_BRANCH
            - | 
              export ACCESS_TOKEN=$(curl -s -S -f -X POST -u "${BITBUCKET_KEY}:${BITBUCKET_SECRET}" \
                https://bitbucket.org/site/oauth2/access_token \
                -d grant_type=client_credentials -d scopes="pullrequests" | jq --raw-output '.access_token')
            - |
              curl -s -X POST \
                -H "Authorization: Bearer ${ACCESS_TOKEN}" \
                -H "Content-Type: application/json" \
                -d '{
                  "title": "'"$PR_TITLE"'",
                  "source": {
                    "branch": { "name": "'"$BITBUCKET_BRANCH"'" }
                  },
                  "destination": {
                    "branch": { "name": "qa" }
                  }
                }' \
                "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_FULL_NAME}/pullrequests"

    "qa":
      - step:
          name: Composer Deploy
          image: threadable/php84-laravel
          script:
            - composer update --prefer-dist --no-interaction --no-progress
            - composer update mirrors

    "dev":
      - step:
          name: Sonar Cloud
          size: 2x
          image: threadable/php84-laravel
          caches:
            - composer
            - docker
          script:
            - composer update --prefer-dist --no-interaction --no-progress --with="illuminate/contracts=^11"
            - vendor/bin/phpunit --display-deprecations --fail-on-deprecation
            - pipe: sonarsource/sonarcloud-scan:2.0.0
              variables:
                DEBUG: "true"
                SONAR_SCANNER_OPTS: -Xmx2048m
            - pipe: sonarsource/sonarcloud-quality-gate:0.1.6
