clone:
  depth: full

options:
  docker: true

image: threadable/linuxnginxphp_ci_20.04:2025.01.01

definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: app
        MYSQL_USER: user
        MYSQL_PASSWORD: password

  steps:
    setup-composer: &setup-composer
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

    update-composer: &update-composer
      - composer update --prefer-dist --no-interaction --no-progress --with="illuminate/contracts=^<LaravelVersion>"
      - php -v
      - composer --version

    phpunit-tests: &phpunit-tests
      - vendor/bin/phpunit --display-deprecations --fail-on-deprecation

    sonarcloud-scan: &sonarcloud-scan
      - pipe: sonarsource/sonarcloud-scan:2.0.0
        variables:
          DEBUG: "true"
          SONAR_SCANNER_OPTS: -Xmx2048m
      - pipe: sonarsource/sonarcloud-quality-gate:0.1.6

pipelines:
  branches:
    "{feature/*,bugfix/*,devops}":
      - step:
          name: Run Tests - PHP 8.1, Laravel 10
          services:
            - mysql
          caches:
            - composer
          script:
            - update-alternatives --set php /usr/bin/php8.1
            - *setup-composer
            - *update-composer
            - *phpunit-tests

      - step:
          name: Run Tests - PHP 8.2, Laravel 10
          services:
            - mysql
          caches:
            - composer
          script:
            - update-alternatives --set php /usr/bin/php8.2
            - *setup-composer
            - *update-composer
            - *phpunit-tests

      - step:
          name: Run Tests - PHP 8.3, Laravel 10
          services:
            - mysql
          caches:
            - composer
          script:
            - update-alternatives --set php /usr/bin/php8.3
            - *setup-composer
            - *update-composer
            - *phpunit-tests

      - step:
          name: Run Tests - PHP 8.2, Laravel 11
          services:
            - mysql
          caches:
            - composer
          script:
            - update-alternatives --set php /usr/bin/php8.2
            - *setup-composer
            - *update-composer
            - *phpunit-tests

      - step:
          name: Run Tests - PHP 8.3, Laravel 11
          services:
            - mysql
          caches:
            - composer
          script:
            - update-alternatives --set php /usr/bin/php8.3
            - *setup-composer
            - *update-composer
            - *phpunit-tests

      - step:
          name: Run Tests - PHP 8.4, Laravel 11
          services:
            - mysql
          caches:
            - composer
          script:
            - update-alternatives --set php /usr/bin/php8.4
            - *setup-composer
            - *update-composer
            - *phpunit-tests
            - *sonarcloud-scan

    "qa":
      - step:
          name: Composer Deploy
          script:
            - update-alternatives --set php /usr/bin/php8.3
            - *setup-composer
            - composer update --prefer-dist --no-interaction --no-progress
            - composer update mirrors
