pipelines:
  branches:
    devops:
      - step:
          name: Run Tests - PHP 8.1, Laravel 10
          image: php:8.1
          services:
            - mysql
          caches:
            - composer
          script:
            - export LARAVEL_VERSION=10
            - *run-tests

      - step:
          name: Run Tests - PHP 8.2, Laravel 10
          image: php:8.2
          services:
            - mysql
          caches:
            - composer
          script:
            - export LARAVEL_VERSION=10
            - *run-tests

      - step:
          name: Run Tests - PHP 8.3, Laravel 10
          image: php:8.3
          services:
            - mysql
          caches:
            - composer
          script:
            - export LARAVEL_VERSION=10
            - *run-tests

      - step:
          name: Run Tests - PHP 8.4, Laravel 10
          image: php:8.4
          services:
            - mysql
          caches:
            - composer
          script:
            - export LARAVEL_VERSION=10
            - *run-tests

      - step:
          name: Run Tests - PHP 8.1, Laravel 11
          image: php:8.1
          services:
            - mysql
          caches:
            - composer
          script:
            - export LARAVEL_VERSION=11
            - *run-tests

      - step:
          name: Run Tests - PHP 8.2, Laravel 11
          image: php:8.2
          services:
            - mysql
          caches:
            - composer
          script:
            - export LARAVEL_VERSION=11
            - *run-tests

      - step:
          name: Run Tests - PHP 8.3, Laravel 11
          image: php:8.3
          services:
            - mysql
          caches:
            - composer
          script:
            - export LARAVEL_VERSION=11
            - *run-tests

      - step:
          name: Run Tests - PHP 8.4, Laravel 11
          image: php:8.4
          services:
            - mysql
          caches:
            - composer
          script:
            - export LARAVEL_VERSION=11
            - *run-tests

definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: app
        MYSQL_USER: user
        MYSQL_PASSWORD: password
  caches:
    composer: ~/.composer/cache
  steps:
    - step: &run-tests
        script:
          - apt-get update && apt-get install -y libxml2-dev libcurl4-openssl-dev libpng-dev libjpeg-dev libfreetype6-dev
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer update --prefer-dist --no-interaction --no-progress --with="illuminate/contracts=^${LARAVEL_VERSION}"
          - vendor/bin/phpunit --display-deprecations --fail-on-deprecation
