clone:
  depth: full

options:
  docker: true

image: threadable/linuxnginxphp_ci_20.04:2025.01.01

definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: app
        MYSQL_USER: user
        MYSQL_PASSWORD: password

pipelines:
  branches:
    "{feature/*,bugfix/*}":

      - step:
          name: Transistion IN CI
          script:
            - export BRANCH_NAME=$(echo $BITBUCKET_BRANCH)
            - echo "Branch Name: $BRANCH_NAME"
            - if [[ $BRANCH_NAME =~ ([A-Z]+-[0-9]+) ]]; then
                export JIRA_ISSUE=${BASH_REMATCH[1]};
                echo "Jira Issue Key: $JIRA_ISSUE";
              else
                echo "No Jira Issue Key found in branch name: $BRANCH_NAME";
                exit 1;
              fi
            - pipe: atlassian/jira-transition:0.5.1
              variables:
                JIRA_BASE_URL: $JIRA_BASE_URL
                JIRA_USER_EMAIL: $JIRA_USER_EMAIL
                JIRA_API_TOKEN: $JIRA_API_TOKEN
                ISSUE: $JIRA_ISSUE
                TRANSITION: 'Submit to CI/CD'

      - step: 
          name: Static Analysis
          caches:
            - composer
          script:
            - update-alternatives --set php /usr/bin/php8.4
            - composer update --prefer-dist --no-interaction --no-progress --with="illuminate/contracts=^11"
            - vendor/bin/phpstan --display-deprecations --fail-on-deprecation
      
      - step:
          name: Run Tests - PHP 8.1, Laravel 10
          services:
            - mysql
          caches:
            - composer
          script:
            - update-alternatives --set php /usr/bin/php8.1
            - composer update --prefer-dist --no-interaction --no-progress --with="illuminate/contracts=^10"
            - vendor/bin/phpunit --display-deprecations --fail-on-deprecation

      - step:
          name: Run Tests - PHP 8.2, Laravel 10
          services:
            - mysql
          caches:
            - composer
          script:
            - update-alternatives --set php /usr/bin/php8.2
            - composer update --prefer-dist --no-interaction --no-progress --with="illuminate/contracts=^10"
            - vendor/bin/phpunit --display-deprecations --fail-on-deprecation

      - step:
          name: Run Tests - PHP 8.3, Laravel 10
          services:
            - mysql
          caches:
            - composer
          script:
            - update-alternatives --set php /usr/bin/php8.3
            - composer update --prefer-dist --no-interaction --no-progress --with="illuminate/contracts=^10"
            - vendor/bin/phpunit --display-deprecations --fail-on-deprecation

      - step:
          name: Run Tests - PHP 8.2, Laravel 11
          services:
            - mysql
          caches:
            - composer
          script:
            - update-alternatives --set php /usr/bin/php8.2
            - composer update --prefer-dist --no-interaction --no-progress --with="illuminate/contracts=^11"
            - vendor/bin/phpunit --display-deprecations --fail-on-deprecation

      - step:
          name: Run Tests - PHP 8.3, Laravel 11
          services:
            - mysql
          caches:
            - composer
          script:
            - update-alternatives --set php /usr/bin/php8.3
            - composer update --prefer-dist --no-interaction --no-progress --with="illuminate/contracts=^11"
            - vendor/bin/phpunit --display-deprecations --fail-on-deprecation

      - step:
          name: Run Tests - PHP 8.4, Laravel 11 & Code Coverage
          services:
            - mysql
          caches:
            - composer
          script:
            - update-alternatives --set php /usr/bin/php8.4
            - apt install -y php8.4-common php8.4-{bcmath,bz2,curl,gd,gmp,intl,mbstring,opcache,readline,xml,zip,xdebug,dom}
            - composer update --prefer-dist --no-interaction --no-progress --with="illuminate/contracts=^11"
            - vendor/bin/phpunit --display-deprecations --fail-on-deprecation
            - pipe: sonarsource/sonarcloud-scan:2.0.0
              variables:
                DEBUG: "true"
                SONAR_SCANNER_OPTS: -Xmx2048m
            - pipe: sonarsource/sonarcloud-quality-gate:0.1.6

    "qa":
      - step:
          name: Composer Deploy
          script:
            - update-alternatives --set php /usr/bin/php8.4
            - composer update --prefer-dist --no-interaction --no-progress
            - composer update mirrors
