name: Static Analysis and Tests

on:
  push:
    branches:
      - master
      - "*.x"
  pull_request:

permissions:
  contents: read

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    name: Static Analysis

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: swoole, relay
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command:
            composer update --prefer-stable --prefer-dist --no-interaction
            --no-progress

      - name: Execute type checking
        run: vendor/bin/phpstan --verbose
  tests:
    needs: static-analysis
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        php: [ 8.1, 8.2, 8.3, 8.4 ]
        laravel: [ 10, 11, 12 ]
        exclude:
          - php: 8.1
            laravel: 11
          - php: 8.1
            laravel: 12

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, bcmath
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: xdebug

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress --with="illuminate/contracts:^${{ matrix.laravel }}"

      - name: Execute tests
        run: vendor/bin/phpunit --display-deprecations --fail-on-deprecation
        env:
          CHARGEBEE_SITE: ${{ vars.CHARGEBEE_SITE }}
          CHARGEBEE_API_KEY: ${{ secrets.CHARGEBEE_API_KEY }}
